version: '3.3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - creci_net_default

  nginx:
    build: .services/waf
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes: .:/var/www
    networks:
      - creci_net_default

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    networks:
      - creci_net_default

#################################
#########  NETWORKS   ###########
#################################
networks:
  creci_net_default:
    driver: bridge

#################################
#########  SEGURANÇA   ###########
#################################
  # certbot:
  #   depends_on:
  #     - nginx
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com -d www.example.com  

#################################
#########  VOLUMES    ###########
#################################
# volumes:
#   certbot:
#   wordpress:
#   oracle_db: